# Generated by Django 4.2.28 on 2026-03-01 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=10)),
                ('categoria', models.CharField(blank=True, max_length=10)),
                ('turno', models.CharField(choices=[('T1', 'Turno 1'), ('T2', 'Turno 2'), ('T3', 'Turno 3')], max_length=10)),
                ('posicion', models.CharField(choices=[('Por definir', 'Por definir'), ('colocador', 'Colocador'), ('opuesto', 'Opuesto'), ('central', 'Central'), ('libero', 'Libero'), ('punta', 'Punta')], max_length=50)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('numero_camisa', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('salto', models.FloatField(blank=True, help_text='Salto en metros', null=True)),
                ('alcance', models.FloatField(blank=True, help_text='Alcance en metros', null=True)),
                ('peso', models.FloatField(blank=True, help_text='Peso en kilogramos', null=True)),
                ('estatura', models.FloatField(blank=True, help_text='Estatura en metros', null=True)),
                ('representante_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('representante_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('representante_cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('representante_telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('sexo_equipo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('mixto', 'Mixto')], max_length=10, null=True)),
                ('edad_tope', models.PositiveIntegerField(blank=True, null=True)),
                ('atletas', models.ManyToManyField(blank=True, to='atletas.atleta')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('año', models.IntegerField(default=2026)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('exonerado', models.BooleanField(default=False)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='atletas.atleta')),
            ],
            options={
                'ordering': ['año', 'mes'],
                'unique_together': {('atleta', 'mes', 'año')},
            },
        ),
    ]
