# Generated by Django 5.2.1 on 2025-06-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('turno', models.CharField(choices=[('1', 'Turno 1'), ('2', 'Turno 2'), ('3', 'Turno 3')], max_length=10)),
            ],
        ),
    ]
