# Generated by Django 5.2.1 on 2025-06-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='estado_mensualidad',
            field=models.CharField(choices=[('al_dia', 'Al día'), ('deuda', 'Deuda'), ('exonerado', 'Exonerado')], default='Central', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atleta',
            name='posicion',
            field=models.CharField(choices=[('colocador', 'Colocador'), ('opuesto', 'Opuesto'), ('central', 'Central'), ('libero', 'Libero'), ('punteo', 'Punteo')], default='Central', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atleta',
            name='turno',
            field=models.CharField(choices=[('T1', 'Turno 1'), ('T2', 'Turno 2'), ('T3', 'Turno 3')], max_length=2),
        ),
    ]
