# Generated by Django 5.2.1 on 2025-06-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0002_atleta_estado_mensualidad_atleta_posicion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='apellido',
            field=models.CharField(default='central', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atleta',
            name='categoria',
            field=models.CharField(default='Central', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atleta',
            name='cedula',
            field=models.CharField(default='exit', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atleta',
            name='posicion',
            field=models.CharField(choices=[('colocador', 'Colocador'), ('opuesto', 'Opuesto'), ('central', 'Central'), ('libero', 'Libero'), ('punteo', 'Punteo'), ('Por definir', 'Por definir')], default='Por definir', max_length=50),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='turno',
            field=models.CharField(choices=[('T1', 'Turno 1'), ('T2', 'Turno 2'), ('T3', 'Turno 3')], max_length=10),
        ),
    ]
