# Generated by Django 5.2.1 on 2025-06-12 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0003_atleta_apellido_atleta_categoria_atleta_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='atleta',
            name='numero_camisa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='posicion',
            field=models.CharField(default='Por definir', max_length=50),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='turno',
            field=models.CharField(max_length=10),
        ),
    ]
