# Generated by Django 5.2.1 on 2025-06-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0004_atleta_fecha_registro_atleta_numero_camisa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='numero_camisa',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atleta',
            name='posicion',
            field=models.CharField(choices=[('Por definir', 'Por definir'), ('colocador', 'Colocador'), ('opuesto', 'Opuesto'), ('central', 'Central'), ('libero', 'Libero'), ('punteo', 'Punteo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='turno',
            field=models.CharField(choices=[('T1', 'Turno 1'), ('T2', 'Turno 2'), ('T3', 'Turno 3')], max_length=10),
        ),
    ]
