# Generated by Django 5.2.1 on 2025-06-12 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0005_alter_atleta_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='numero_camisa',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
