# Generated by Django 5.2.1 on 2025-06-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0006_alter_atleta_numero_camisa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='numero_camisa',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
