# Generated by Django 5.2.1 on 2025-06-14 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0007_alter_atleta_numero_camisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='sexo',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='femenino', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atleta',
            name='categoria',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='posicion',
            field=models.CharField(choices=[('Por definir', 'Por definir'), ('colocador', 'Colocador'), ('opuesto', 'Opuesto'), ('central', 'Central'), ('libero', 'Libero'), ('punta', 'Punta')], max_length=50),
        ),
    ]
