# Generated by Django 5.2.1 on 2025-06-15 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0008_atleta_sexo_alter_atleta_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('año', models.IntegerField(default=2025)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('exonerado', models.BooleanField(default=False)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensualidades', to='atletas.atleta')),
            ],
            options={
                'ordering': ['año', 'mes'],
                'unique_together': {('atleta', 'mes', 'año')},
            },
        ),
    ]
