# Generated by Django 5.2.1 on 2025-06-18 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0009_mensualidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_partido', models.DateField()),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('saques', models.PositiveIntegerField(default=0)),
                ('remates', models.PositiveIntegerField(default=0)),
                ('bloqueos', models.PositiveIntegerField(default=0)),
                ('armadas', models.PositiveIntegerField(default=0)),
                ('recepciones', models.PositiveIntegerField(default=0)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='atletas.atleta')),
            ],
        ),
    ]
