# Generated by Django 5.2.1 on 2025-06-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0010_estadistica'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadistica',
            name='errores',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
