# Generated by Django 5.2.1 on 2025-06-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0011_estadistica_errores'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadistica',
            name='alcance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estadistica',
            name='salto',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
