# Generated by Django 5.2.1 on 2025-06-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0012_estadistica_alcance_estadistica_salto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadistica',
            name='alcance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='salto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
