# Generated by Django 5.2.1 on 2025-06-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0013_alter_estadistica_alcance_alter_estadistica_salto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='alcance',
            field=models.FloatField(blank=True, help_text='En centímetros', null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='salto',
            field=models.FloatField(blank=True, help_text='En centímetros', null=True),
        ),
    ]
