# Generated by Django 5.2.1 on 2025-06-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0014_atleta_alcance_atleta_salto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='estatura',
            field=models.FloatField(blank=True, help_text='Estatura en metros', null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='peso',
            field=models.FloatField(blank=True, help_text='Peso en kilogramos', null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='alcance',
            field=models.FloatField(blank=True, help_text='Alcance en metros', null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='salto',
            field=models.FloatField(blank=True, help_text='Salto en metros', null=True),
        ),
    ]
