# Generated by Django 5.2.1 on 2025-06-28 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0016_entrenador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenador',
            name='usuario',
        ),
    ]
