# Generated by Django 5.2.1 on 2025-06-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0017_remove_entrenador_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('formal', 'Formal'), ('amistoso', 'Amistoso')], max_length=10)),
                ('anio', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
