# Generated by Django 5.2.1 on 2025-06-30 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0018_campeonato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_local', models.CharField(max_length=100)),
                ('equipo_externo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=150)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('set1_local', models.PositiveIntegerField(blank=True, null=True)),
                ('set1_externo', models.PositiveIntegerField(blank=True, null=True)),
                ('set2_local', models.PositiveIntegerField(blank=True, null=True)),
                ('set2_externo', models.PositiveIntegerField(blank=True, null=True)),
                ('set3_local', models.PositiveIntegerField(blank=True, null=True)),
                ('set3_externo', models.PositiveIntegerField(blank=True, null=True)),
                ('set4_local', models.PositiveIntegerField(blank=True, null=True)),
                ('set4_externo', models.PositiveIntegerField(blank=True, null=True)),
                ('set5_local', models.PositiveIntegerField(blank=True, null=True)),
                ('set5_externo', models.PositiveIntegerField(blank=True, null=True)),
                ('campeonato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atletas.campeonato')),
            ],
        ),
    ]
