# Generated by Django 5.2.1 on 2025-07-01 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0019_partido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=20)),
                ('es_interno', models.BooleanField(default=True)),
                ('atletas', models.ManyToManyField(related_name='equipos', to='atletas.atleta')),
                ('entrenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='atletas.entrenador')),
            ],
        ),
    ]
