# Generated by Django 5.2.1 on 2025-07-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0020_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='sexo_equipo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Mixto', 'Mixto')], default='Mixto', max_length=10),
        ),
    ]
