# Generated by Django 5.2.1 on 2025-07-02 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0021_equipo_sexo_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='atletas',
            field=models.ManyToManyField(to='atletas.atleta'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atletas.entrenador'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='sexo_equipo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('mixto', 'Mixto')], max_length=10, null=True),
        ),
    ]
