# Generated by Django 5.2.1 on 2025-07-04 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0022_alter_equipo_atletas_alter_equipo_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='es_interno',
        ),
    ]
