# Generated by Django 5.2.1 on 2025-07-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0023_remove_equipo_es_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='edad_tope',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
