# Generated by Django 5.2.1 on 2025-07-04 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0024_equipo_edad_tope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='equipo_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='atletas.equipo'),
        ),
    ]
