# Generated by Django 5.2.1 on 2025-07-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0025_alter_partido_equipo_escovol'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='formato_partido',
            field=models.CharField(choices=[('3-2', 'Ganar 2 de 3 sets'), ('5-3', 'Ganar 3 de 5 sets')], default='5-3', max_length=5),
        ),
        migrations.AddField(
            model_name='partido',
            name='ganador',
            field=models.CharField(blank=True, choices=[('escovol', 'Escovol'), ('externo', 'Equipo Externo')], max_length=20, null=True),
        ),
    ]
