# Generated by Django 5.2.1 on 2025-07-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0026_partido_formato_partido_partido_ganador'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='representante_apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='representante_cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='representante_nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='representante_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
