# Generated by Django 5.2.1 on 2025-07-09 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0027_atleta_direccion_atleta_representante_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadistica',
            name='fecha_partido',
        ),
        migrations.AddField(
            model_name='estadistica',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='atletas.partido'),
        ),
    ]
