# Generated by Django 5.2.1 on 2025-07-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0028_remove_estadistica_fecha_partido_estadistica_partido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='estado_mensualidad',
        ),
        migrations.AlterField(
            model_name='mensualidad',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
