# Generated by Django 5.2.1 on 2025-09-01 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0030_atleta_user_entrenador_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrenador',
            name='email',
        ),
    ]
