# Generated by Django 5.2.1 on 2025-09-03 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0032_administrador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='email',
        ),
    ]
