# Generated by Django 4.2.15 on 2026-02-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0033_remove_administrador_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensualidad',
            name='año',
            field=models.IntegerField(default=2026),
        ),
        migrations.AlterField(
            model_name='partido',
            name='ganador',
            field=models.CharField(
                blank=True,
                choices=[
                    ('local', 'Equipo Local'),
                    ('externo', 'Equipo Externo'),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]