# Generated by Django 4.2.28 on 2026-09-03 18:42

import atletas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0034_rename_equipo_escovol_partido_equipo_local_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='mensualidad',
                    name='año',
                    field=models.IntegerField(default=atletas.models.anio_actual),
                ),
            ],
        ),
    ]