# Generated by Django 5.2.17 on 2026-09-14 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0035_alter_mensualidad_año'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='entrenador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atletas.entrenador'),
        ),
        migrations.AlterField(
            model_name='estadistica',
            name='partido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estadisticas', to='atletas.partido'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='campeonato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='atletas.campeonato'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='equipo_local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidos', to='atletas.equipo'),
        ),
    ]
